In [64]:
import numpy as np

In [65]:
data = np.genfromtxt('/Users/sebastian/Desktop/willett0.dat')

In [67]:
print(data)
print(data.shape)

[[ 0.00103259 -0.28150482  0.        ]
 [ 0.00101152 -0.28149838  0.        ]
 [ 0.00099044 -0.28148869  0.        ]
 ...
 [ 0.0241289   0.          0.        ]
 [ 0.02414997  0.          0.        ]
 [ 0.02417105  0.          0.        ]]
(1148, 3)


In [76]:
temp = data[0:50,:]
print(temp)
print(temp.shape)

[[ 1.03259046e-03 -2.81504823e-01  0.00000000e+00]
 [ 1.01151718e-03 -2.81498381e-01  0.00000000e+00]
 [ 9.90443910e-04 -2.81488694e-01  0.00000000e+00]
 [ 9.69370635e-04 -2.81474124e-01  0.00000000e+00]
 [ 9.48297361e-04 -2.81452213e-01  0.00000000e+00]
 [ 9.27224086e-04 -2.81419264e-01  0.00000000e+00]
 [ 9.06150811e-04 -2.81369723e-01  0.00000000e+00]
 [ 8.85077537e-04 -2.81295242e-01  0.00000000e+00]
 [ 8.64004262e-04 -2.81183293e-01  0.00000000e+00]
 [ 8.42930987e-04 -2.81015084e-01  0.00000000e+00]
 [ 8.21857713e-04 -2.80762468e-01  0.00000000e+00]
 [ 8.00784438e-04 -2.80383373e-01  0.00000000e+00]
 [ 7.79711163e-04 -2.79815119e-01  0.00000000e+00]
 [ 7.58637889e-04 -2.78964759e-01  0.00000000e+00]
 [ 7.37564614e-04 -2.77695462e-01  0.00000000e+00]
 [ 7.16491339e-04 -2.75807975e-01  0.00000000e+00]
 [ 6.95418065e-04 -2.73016924e-01  0.00000000e+00]
 [ 6.74344790e-04 -2.68923816e-01  0.00000000e+00]
 [ 6.53271515e-04 -2.62993581e-01  0.00000000e+00]
 [ 6.32198241e-04 -2.54550901e-

In [77]:
temp = np.flipud(temp)
print(temp)

[[ 0.00000000e+00 -1.27802992e-05  0.00000000e+00]
 [ 2.10732747e-05 -1.92218037e-05  0.00000000e+00]
 [ 4.21465494e-05 -2.89096107e-05  0.00000000e+00]
 [ 6.32198241e-05 -4.34793275e-05  0.00000000e+00]
 [ 8.42930987e-05 -6.53901094e-05  0.00000000e+00]
 [ 1.05366373e-04 -9.83386572e-05  0.00000000e+00]
 [ 1.26439648e-04 -1.47880485e-04  0.00000000e+00]
 [ 1.47512923e-04 -2.22361167e-04  0.00000000e+00]
 [ 1.68586197e-04 -3.34309813e-04  0.00000000e+00]
 [ 1.89659472e-04 -5.02518782e-04  0.00000000e+00]
 [ 2.10732747e-04 -7.55135296e-04  0.00000000e+00]
 [ 2.31806022e-04 -1.13422974e-03  0.00000000e+00]
 [ 2.52879296e-04 -1.70248386e-03  0.00000000e+00]
 [ 2.73952571e-04 -2.55284370e-03  0.00000000e+00]
 [ 2.95025846e-04 -3.82214112e-03  0.00000000e+00]
 [ 3.16099120e-04 -5.70962793e-03  0.00000000e+00]
 [ 3.37172395e-04 -8.50067891e-03  0.00000000e+00]
 [ 3.58245670e-04 -1.25937875e-02  0.00000000e+00]
 [ 3.79318944e-04 -1.85240224e-02  0.00000000e+00]
 [ 4.00392219e-04 -2.69667024e-

In [78]:
data[0:50,:] = temp

In [79]:
print(data)

[[ 0.00000000e+00 -1.27802992e-05  0.00000000e+00]
 [ 2.10732747e-05 -1.92218037e-05  0.00000000e+00]
 [ 4.21465494e-05 -2.89096107e-05  0.00000000e+00]
 ...
 [ 2.41288995e-02  0.00000000e+00  0.00000000e+00]
 [ 2.41499728e-02  0.00000000e+00  0.00000000e+00]
 [ 2.41710461e-02  0.00000000e+00  0.00000000e+00]]


In [80]:
np.savetxt('/Users/sebastian/Desktop/willett0.dat', data)